# Generated by Django 3.1.2 on 2020-10-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('disease_photo', models.ImageField(upload_to='')),
                ('disease_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('discription', models.TextField()),
                ('slug', models.SlugField()),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('disease', models.ManyToManyField(blank=True, to='pages.Disease')),
            ],
        ),
    ]
