# Generated by Django 3.1.2 on 2020-11-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
